[package]
name = "runner-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.2"
clap = { version = "4.0.12", features = ["derive"] }
hex = "0.4"
primitive-types = { version = "0.12", features = ["rlp"] }
revm = "2.1.0"
