[package]
name = "runner-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3"
clap = { version = "4.0.26", features = ["derive"] }
hex = "0.4"
primitive-types = { version = "0.11", features = ["rlp"] }
revm = "2.3.1"
