[package]
name = "runner-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4"
clap = { version = "4.2.2", features = ["derive"] }
hex = "0.4"
primitive-types = { version = "0.12.1", features = ["rlp"] }
revm-interpreter = "1.1.1"

