FROM python:latest

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /runner/
COPY pyproject.toml poetry.lock runner.py ./

RUN poetry check --lock
RUN poetry install

ENTRYPOINT [ "poetry", "run", "python", "runner.py" ]